#!/usr/bin/env bash
set -euo pipefail

: "${PROJECT_CACHE_ROOT:=${REPO_ROOT:-$PWD}/.cache_project}"
: "${PROJECT_SCRATCH_ROOT:=${REPO_ROOT:-$PWD}/.scratch}"

export HF_HOME="${HF_HOME:-$PROJECT_CACHE_ROOT/hf/misc}"
export HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-$PROJECT_CACHE_ROOT/hf/datasets}"
export TORCH_HOME="${TORCH_HOME:-$PROJECT_CACHE_ROOT/torch}"
export WANDB_DIR="${WANDB_DIR:-$PROJECT_CACHE_ROOT/wandb}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$PROJECT_CACHE_ROOT/xdg}"
export TMPDIR="${TMPDIR:-$PROJECT_SCRATCH_ROOT/tmp}"

mkdir -p "$HF_HOME" "$HF_DATASETS_CACHE" "$TORCH_HOME" "$WANDB_DIR" "$XDG_CACHE_HOME" "$TMPDIR"

export TRANSFORMERS_OFFLINE="${TRANSFORMERS_OFFLINE:-0}"
export HF_DATASETS_OFFLINE="${HF_DATASETS_OFFLINE:-0}"
